spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel?useSSL=false&serverTimezone=UTC
    username: root
    password: 878878
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml