spring:
  datasource:
    url: jdbc:mysql://172.30.2.200:3309/traveler?useSSL=false&serverTimezone=UTC
    username: root
    password: kms900326
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml