spring:
  datasource:
    url: jdbc:mysql://172.30.2.200:3309/traveler?useSSL=false&serverTimezone=UTC
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration-properties:
    defaultStatementTimeout: 25